#+title: Zsh Config
#+author: Ian Kollipara
#+date: Jun 4, 2022
#+property: header-args :tangle .zshrc

* Introduction
I use Zsh as my primary shell. I really like its capabilities, and its got some niceties that bash doesn't. For my configuration, I use a few plugins, which can be installed by running ~make zsh-install~.

* Environment Variables
To help keep my directories clean, in part aided by [[https://github.com/b3nj5m1n/xdg-ninja][xdg-ninja]], I set a few environment variables.
#+begin_src shell
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
#+end_src
** Home Folder Cleanup
As I mentioned earlier, I like a clean home. So, following the directions of xdg-ninja, I have a few more things I add.
#+begin_src shell
export CABAL_CONFIG="$XDG_CONFIG_HOME/cabal/config"
export CABAL_DIR="$XDG_DATA_HOME/cabal"

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GHCUP_USE_XDG_DIRS=true

export LEIN_HOME="$XDG_DATA_HOME/lein"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"

export POETRY_HOME="$XDG_DATA_HOME/poetry"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export SDKMAN_DIR="$XDG_DATA_HOME/sdkman"

alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

export WINEPREFIX="$XDG_DATA_HOME/wine"
#+end_src
** Path
I add a few directories to my PATH. Most notably ~.local~ and ~.config/emacs/bin~.
#+begin_src shell
export PATH="$HOME/.local/bin:$HOME/.config/emacs/bin:$PATH"
#+end_src

* Aliases
I use a few important aliases for moving around my file system easier. The most complicated of which is ~ls~, which is overridden to use [[https://github.com/ogham/exa][exa]].
#+begin_src shell
alias h="cd"
alias cls="clear"
alias b="cd .."
alias ls="exa"
#+end_src

* Stylization
I do like my terminal to be pretty, so I use [[https://starship.rs/][Starship: Cross-Shell Prompt]] and [[https://github.com/zsh-users/zsh-syntax-highlighting][zsh-syntax-highlighting]]. Another thing I do, that's related but not perfectly fit here is the vim keybindings I use for the terminal.
#+begin_src shell
bindkey -v
source "/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
eval "$(starship init zsh)"
#+end_src
