theme = "vague"

[editor]
line-number = "relative"
text-width = 120
popup-border = "all"
color-modes = true
default-yank-register = '+'

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
center = ["version-control"]
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
C-y = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"

[keys.select]
0 = "goto_line_start"
