customCommands:
  - key: "C"
    command: "better-commits"
    description: "commit with better-commits"
    context: "files"
    loadingText: "opening better-commits commit tool"
    subprocess: true
