code --install-extension auiworks.amvim
code --install-extension bibhasdn.django-html
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension christian-kohler.path-intellisense
code --install-extension ecmel.vscode-html-css
code --install-extension editorconfig.editorconfig
code --install-extension enkia.tokyo-night
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension ionide.ionide-fsharp
code --install-extension laravel.vscode-laravel
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension neilbrayfield.php-docblocker
code --install-extension pkief.material-icon-theme
code --install-extension shufo.vscode-blade-formatter
code --install-extension somewhatstationery.some-sass
code --install-extension yeannylam.recenter-top-bottom
