alias h="cd"
alias ls="exa --icons"
alias ll="exa -l --icons -h"
alias b="cd .."
alias cdg="gum choose $HOME/Projects/CPT $HOME/Projects/UNL $HOME/Projects/Work $HOME/Projects/Personal | cd"
alias n="nvim -c \"Telescope find_files\""
alias np="tmux"
alias lg="lazygit"
